// src/constants/assets.ts

export const assets = {
  images: {
    logo: "/assets/images/logo.svg",
    hrSearchText: "/assets/images/hr-search-text.png",
  },
  icons: {
    eye: "/assets/icons/eyeIcon.svg",
    dashboard: "/assets/icons/dashboardIcon.svg",
    users: "/assets/icons/usersIcon.png",
    calendar: "/assets/icons/calendarIcon.svg",
    settings: "/assets/icons/settingsIcon.svg",
    moon: "/assets/icons/moonIcon.svg",
    sun: "/assets/icons/sunIcon.svg",
    leaves: "/assets/icons/leavesIcon.svg",
    leave: "/assets/icons/leaves.png",
    employees: "/assets/icons/employees.png",
    attendance: "/assets/icons/attendance.png",
    projects: "/assets/icons/projects.png",
    plus: "/assets/icons/plus.svg",
    filter: "/assets/icons/filter.svg",
    delete: "/assets/icons/delete.svg",
    view: "/assets/icons/view.svg",
    edit: "/assets/icons/edit.svg",
    editAvatar: "/assets/icons/edit-avatar.png",
    upload: "/assets/icons/upload.png",
    camera: "/assets/icons/camera.svg",
    user: "/assets/icons/user.png",
    briefcase: "/assets/icons/briefcase.png",
    document: "/assets/icons/document.svg",
    lock: "/assets/icons/lock.svg",
    mail: "/assets/icons/mail.svg",
    project: "/assets/icons/project.svg",
    download: "/assets/icons/download.svg",
    bell: "/assets/icons/bell.svg",
    defaultAvatar: "/assets/images/default-avatar.png",
    check: "/assets/icons/check.png",
    save: "/assets/icons/save.png",
  },
};
